Diploma/Controllers/LectureController.cs
using DataAccess.Context;
using Diploma.Models;
using Domain.Models.Files;
using Domain.Models.Games;
using Domain.Models.Lectures;
using DomainServices.Games;
using DomainServices.WorkContexts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Diploma.Controllers
{
    public class LectureController : BaseController
    {
        private DataContext _dataContext;
        private WorkContextAccessor _workContextAccessor;
        private IWebHostEnvironment _webHostEnvironment;

        public LectureController(WorkContextAccessor workContextAccessor, DataContext dataContext, IWebHostEnvironment webHostEnvironment)
            : base(workContextAccessor, dataContext)
        {
            _dataContext = dataContext;
            _workContextAccessor = workContextAccessor;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Add(int gameId)
        {
            var addLectureModel = new AddLectureModel()
            {
                GameId = gameId
            };

            return View(addLectureModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddLectureModel addLectureModel)
        {
            if (ModelState.IsValid)
            {
                var companyId = _workContextAccessor.WorkContext.CompanyId;

                Image previewFile = null;
                if (addLectureModel.Preview != null)
                {
                    var fileName = addLectureModel.Preview.FileName;
                    using (var fileStream = new System.IO.FileStream(System.IO.Path.Combine(_webHostEnvironment.WebRootPath, "Files", "Lectures", "Previewes", fileName), System.IO.FileMode.Create))
                    {
                        await addLectureModel.Preview.CopyToAsync(fileStream);
                    }

                    previewFile = new Image
                    {
                        Name = fileName,
                        Path = "~/Files/Lectures/Previewes" + addLectureModel.Preview.FileName
                    };
                }

                Domain.Models.Files.File materialFile = null;
                if (addLectureModel.Material != null)
                {
                    var fileName = addLectureModel.Material.FileName;
                    using (var fileStream = new System.IO.FileStream(System.IO.Path.Combine(_webHostEnvironment.WebRootPath, "Files", "Lectures", "Materials", fileName), System.IO.FileMode.Create))
                    {
                        await addLectureModel.Material.CopyToAsync(fileStream);
                    }

                    materialFile = new Domain.Models.Files.File
                    {
                        Name = fileName,
                        Path = "~/Files/Lectures/Materials" + addLectureModel.Material.FileName
                    };
                }

                var games = new List<Game>();
                games.Add(_dataContext.Games.FirstOrDefault(g => g.Id == addLectureModel.GameId));

                _dataContext.Add(new CustomLecture
                {
                    LectureName = addLectureModel.Name,
                    Preview = previewFile,
                    Material = materialFile,
                    Games = games,
                    AuthorCompany = _dataContext.Companies.FirstOrDefault(c => c.Id == companyId),
                    IsPublic = addLectureModel.IsPublic
                });
                await _dataContext.SaveChangesAsync();

                return RedirectToAction("Details", "Game", new {gameId = addLectureModel.GameId, partType = GamePartType.Lecture});
            }

            return View(addLectureModel);
        }

        public IActionResult GetLecture(int lectureId)
        {
            var lectureMaterial = _dataContext.Lectures.WithMaterial().FirstOrDefault(l => l.Id == lectureId).Material;
            var filePath = Path.Combine("Files", "Lectures", "Materials", lectureMaterial.Name);

            return File(filePath, "text/plain", lectureMaterial.Name);
        }
    }
}

Diploma/Views/Lecture/Add.cshtml
@model Diploma.Models.AddLectureModel

@{
    ViewData["Title"] = "Добавление лекции";
    Layout = "_BaseLayout";
}

<div class="text-center">
    <h1>Добавление лекции</h1>
</div>

<hr />

<div class="container">
    <form asp-controller="Lecture" asp-action="Add" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row justify-content-md-center">
            <div class="col-5">
                <div class="text-center">
                    <h4>Описание игры</h4>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsPublic" /> @Html.DisplayNameFor(model => model.IsPublic)
                    </label>
                </div>
            </div>
            <div class="col-5">
                <div class="text-center">
                    <h4>Файлы для добавления</h4>
                </div>
                <div class="form-group">
                    <label asp-for="Preview" class="control-label"></label>
                    <input asp-for="Preview" class="form-control" />
                    <span asp-validation-for="Preview" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Material" class="control-label"></label>
                    <input asp-for="Material" class="form-control" />
                    <span asp-validation-for="Material" class="text-danger"></span>
                </div>
            </div>
            <input asp-for="GameId" type="hidden" class="form-control" />
            <h4></h4>
            <div class="form-group text-center">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>