Diploma/Controllers/StatisticController.cs
using DataAccess.Context;
using Diploma.Models;
using Domain.Models.Users;
using Domain.Models.UserTests;
using DomainServices.Users;
using DomainServices.WorkContexts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;

namespace Diploma.Controllers
{
    public class StatisticController : BaseController
    {
        private UserManager<User> _userManager;
        private DataContext _dataContext;
        private SignInManager<User> _signInManager;
        private UserServices _userServices;

        public StatisticController(WorkContextAccessor workContextAccessor, UserManager<User> userManager, DataContext dataContext,
            UserServices userServices, SignInManager<User> signInManager = null)
            : base(workContextAccessor, dataContext)
        {
            _userManager = userManager;
            _dataContext = dataContext;
            _signInManager = signInManager;
            _userServices = userServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_workContextAccessor.WorkContext.IsCompanyMember == true)
            {
                var statisticModels = new List<StatisticModel>();

                var userTests = _dataContext.UserTests
                    .WithTest()
                    .Where(ut => ut.UserId == _workContextAccessor.WorkContext.UserId)
                    .Select(ut => new { Points = ut.Points, Test = ut.Test, UserId = ut.UserId})
                    .ToList();

                foreach (var userTest in userTests)
                {
                    statisticModels.Add(new StatisticModel
                    {
                        TestId = userTest.Test.Id,
                        UserId = userTest.UserId,
                        TestName = userTest.Test.Name,
                        TestStage = userTest.Test.TopicStage,
                        UserPoints = userTest.Points.Value,
                        MaxPointsForTest = userTest.Test.MaxPoints(),
                        PointInPersent = Math.Round( ((float) userTest.Points.Value / (float) userTest.Test.MaxPoints()*100),2)
                    });
                }

                return View("IndexForMember",statisticModels);

            }
            else if (_workContextAccessor.WorkContext.IsCompanyAdmin == true)
            {
                var statisticAdminModels = new List<StatisticModelForAdmin>();
                var adminId = _workContextAccessor.WorkContext.CompanyId;

                var userTestsForAdmin = _dataContext.UserTests
                    .WithTest()
                    .Where(ut => ut.User.Company.Id == adminId)
                    .Select(ut => new { UserName = ut.User, Points = ut.Points, Test = ut.Test })
                    .ToList();

                foreach (var userTest in userTestsForAdmin)
                {
                    statisticAdminModels.Add(new StatisticModelForAdmin
                    {
                        UserName = userTest.UserName.Surname,
                        TestName = userTest.Test.Name,
                        TestStage = userTest.Test.TopicStage,
                        UserPoints = userTest.Points.Value,
                        MaxPointsForTest = userTest.Test.MaxPoints(),
                        PointInPersent = Math.Round(((float)userTest.Points.Value / (float)userTest.Test.MaxPoints() * 100), 2)
                    });
                }

                return View("IndexForAdmin", statisticAdminModels);
            }
            return View();
        }

        public async Task<IActionResult> FullStatistic(int testId, int userId)
        {
            var fullStatistic = new StatisticTestModel();

            var userTest = _dataContext.UserTests
                .WithTest()
                .WithQuestion()
                .FirstOrDefault(ut => ut.TestId == testId && ut.UserId == userId);

            fullStatistic.TestId = userTest.TestId;

            foreach (var question in userTest.Test.Questions)
            {
                fullStatistic.StatisticQuestionModels.Add(new StatisticQuestionModel
                {
                    QuestionId = question.Id,
                    QuestionText = question.Text,
                    Answers = question.Answers.Select(a => new AnswerModel(a.Id, a.Text)).ToList(),
                    CorrectAnswerIds = question.Answers.Where(a => a.Points > 0).Select(a => a.Id).ToList(),
                    UserPoints = userTest.UserTestQuestions.FirstOrDefault(utq => utq.QuestionId == question.Id).Points,
                    MaxPointsForQuestion = question.Points().Value
                });
            }

            return View(fullStatistic);
        }
    }
}

Diploma/Views/Statistic/FullStatistic.cshtml
@model StatisticTestModel
@{
    ViewData["Title"] = "Статистика";
    Layout = "_BaseLayout";
}

<div class="text-center">
    <h1>Статистика по тесту</h1>
</div>

<hr />

<div class="container">
    <div class="row justify-content-md-center">

        @foreach (var question in Model.StatisticQuestionModels)
        {
            <div class="card border-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">@Html.Raw(question.QuestionText)</div>
                <div class="card-body">
                    <h5 class="card-title">Варианты ответов:</h5>
                    @foreach (var answer in question.Answers)
                    {
                        if (question.CorrectAnswerIds.Contains(answer.Id))
                        {
                            <p class="card-text" style="color:#00FF00">@answer.Text</p>
                        }
                        else
                        {
                            <p class="card-text">@answer.Text</p>
                        }
                    }
                    <div class="alert alert-dismissible alert-light">
                        <h6 class="card-title">Максимальный балл за вопрос: @question.MaxPointsForQuestion</h6>
                        <h6 class="card-title" style="color: #000000">Ваш балл за вопрос: @question.UserPoints</h6>
                    </div>

                </div>
            </div>
        }

    </div>
</div>

Diploma/Views/Statistic/IndexForAdmin.cshtml
@model ICollection<StatisticModelForAdmin>
@{
    ViewData["Title"] = "Статистика";
    Layout = "_BaseLayout";
}

<div class="text-center">
    <h1>Статистика</h1>
</div>

<hr />

<div class="container">
    <form asp-controller="Statictic" asp-action="GetStatistic" method="get" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row justify-content-md-center">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Фамилия участника</th>
                        <th scope="col">Название тестирования</th>
                        <th scope="col">Этап</th>
                        <th scope="col">Набранные баллы</th>
                        <th scope="col">Максимальное количство баллов</th>
                        <th scope="col">Правильные ответы в %</th>
                    </tr>
                </thead>
                @foreach (var test in Model)
                {
                    <tbody>
                        <tr class="table-dark">
                            <td>@test.UserName</td>
                            <td>@test.TestName</td>
                            @switch (test.TestStage)
                            {
                                case Domain.Models.Tests.TopicStage.PreliminaryTest:
                                    <td>Входное тестирование</td>
                                    break;
                                case Domain.Models.Tests.TopicStage.Game:
                                    <td>Игра</td>
                                    break;
                                case Domain.Models.Tests.TopicStage.FinalTest:
                                    <td>Итоговое тестирование</td>
                                    break;
                            }
                            <td>@test.UserPoints</td>
                            <td>@test.MaxPointsForTest</td>
                            <td>@test.PointInPersent</td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
    </form>
</div>

Diploma/Views/Statistic/IndexForMember.cshtml
@model ICollection<StatisticModel>
@{
    ViewData["Title"] = "Статистика";
    Layout = "_BaseLayout";
}

<div class="text-center">
    <h1>Статистика</h1>
</div>

<hr />

<div class="container">
    <div class="row justify-content-md-center">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Название тестирования</th>
                    <th scope="col">Этап</th>
                    <th scope="col">Набранные баллы</th>
                    <th scope="col">Максимальное количство баллов</th>
                    <th scope="col">Правильные ответы в %</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var statistic in Model)
                {
                    <tr class="table-dark">
                        <td>
                            <div>
                                <a asp-controller="Statistic" asp-action="FullStatistic" asp-route-testId="@statistic.TestId" asp-route-userId="@statistic.UserId" style="text-decoration: none;">@statistic.TestName</a>                                
                            </div>
                        </td>
                        @switch (statistic.TestStage)
                        {
                            case Domain.Models.Tests.TopicStage.PreliminaryTest:
                                <td>Входное тестирование</td>
                                break;
                            case Domain.Models.Tests.TopicStage.Game:
                                <td>Игра</td>
                                break;
                            case Domain.Models.Tests.TopicStage.FinalTest:
                                <td>Итоговое тестирование</td>
                                break;
                        }
                        <td>@statistic.UserPoints</td>
                        <td>@statistic.MaxPointsForTest</td>
                        <td>@statistic.PointInPersent</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>